name: Simple Test

on:
  push:
    branches:
      - _master
  pull_request:
    branches:
      - _master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Lua
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: "5.4"
      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4
      - name: Install dependencies
        run: |
          luarocks install busted
      - name: Run tests
        run: busted tests/utils_spec.lua
