name: github-release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ####################
  # test
  ####################

  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ["nightly", "stable"]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run tests
        uses: nvim-neorocks/nvim-busted-action@v1
        with:
          nvim_version: ${{ matrix.neovim_version }}

  ####################
  # github-release
  ####################

  github-release:
    name: github-release
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: init release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json

      - name: checkout
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: release
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/google-github-actions/release-please-action.git"
          git tag -d stable || true
          git push origin :stable || true
          git tag -a stable -m "Last Stable Release"
          git push origin stable
