name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple
          package-name: mindmap

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Create Release ZIP
        if: ${{ steps.release.outputs.release_created }}
        run: |
          zip -r mindmap-${{ steps.release.outputs.tag_name }}.zip . -x '*.git*'

      - name: Upload Release Asset
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} mindmap-${{ steps.release.outputs.tag_name }}.zip

      - name: Tag stable version
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git tag -d stable || true
          git push origin :stable || true
          git tag -a stable -m "Last Stable Release"
          git push origin stable
